language: node_js
node_js:
  - 14

before_install:
  - node --version
  - npm --version
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

install:
  - npm install -g serverless

script:
  - serverless deploy